#!/bin/tcsh

# ANSI COLOR code
set ANSI_GRAY="\033[40;37m"
set ANSI_RED="\033[41;37m"
set ANSI_GREEN="\033[42;37m"
set ANSI_YELLOW="\033[43;37m"
set ANSI_BLUE="\033[44;37m"
set ANSI_PURPLE="\033[45;37m"
set ANSI_NORMAL="\033[0m"

set FIDS = "$*"

foreach d ($FIDS)
 if (-e $d/fid.com) then
  echo ${d}
 else
  echo ${ANSI_PURPLE}${d}${ANSI_NORMAL}
 endif
end
